CREATE TABLE IF NOT EXISTS participants (
    id UUID PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    UNIQUE (name, email)
);

ALTER TABLE participants
ADD COLUMN IF NOT EXISTS status SMALLINT DEFAULT 1,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
